import Modal from '@/components/Modal'
import './globals.css'
import type { Metadata } from 'next'




export const metadata: Metadata = {
  title: 'trello',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-[#f5f6f8] w-screen h-screen text-gray-700'>
      
        {children}
        <Modal />
        </body>
    </html>
  )
}
